spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true # querydsl sql문 확인
    database: h2

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace